config/routes.rb
Papododia::Application.routes.draw do
  resources :posts

  resources :authors

  resources :categories

  get "home/index"

  root 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base

  #has_admin

end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author
  belongs_to :category
  mount_uploader :image, ImageUploader
  mount_uploader :image2, ImageUploader
  # has_attached_file :avatar, :styles => {:thumb => "293x356>", :banner => "1000x580>"}
  #validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/admin/admin_users_controller.rb
class Admin::AdminUsersController < Admin::ResourcesController
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < Admin::ResourcesController
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ResourcesController
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ResourcesController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render action: 'show', status: :created, location: @author }
      else
        format.html { render action: 'new' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@posts = Post.all
	@categories = Category.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :content, :date, :image, :image_file_name, :author_id, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
		
	<div id="theme-wrapper" >
		
			<header>						
		<div class="branding-wrap text-logo hide-for-small">				
		  <ul id="filter" data-filter="isotope-item">
		       
                        <li><a href="#" data-filter="isotope-item" class="tiptip " title="Todos"></a></li>
			<% @categories.each do |category| %>
			<li><%= link_to "", category, {:'data-filter' => category.name, :'title' => category.name } %></li>
			<% end %>
                      
                    </ul>
				</div><!-- END .branding-wrap.hide-for-small -->
					
				<div id="header-container" class="hide-for-small" >
					<span class="menu-icon"></span>
				</div><!-- END #header-container.hide-for-small -->	
			</header>
				
	
		
<div id="primary-container" class="portfolio-template">

<div id="isotope-container" class="animated BeanFadeIn isotope">

<% @posts.each do |post| %>	


<!-- post a post do blog no bloco -->
<li class="portfolio type-portfolio <%= post.category.name %> isotope-item">	
        <span class="overlay-meta-wrapper hover-on">
        <ul>
            <li class="animated BeanBounceIn"><a href="#" class="tweetlink">Twitter Share</a></li>
            <li class="animated BeanBounceIn"><a href="#" class="facelink">Facebook Share</a></li>
          
        </ul>
        </span><!-- END .overlay-meta-wrapper -->
	<%= link_to(post, :class => 'hover-on') do %>
        
            <div class="hoverdiv-feat hide-for-small">
	     <%= image_tag(post.image_url(:giga)) %>
         		
            </div>
            
            <div class="overlay hover-on">
                <h4><%= post.title %> <span><%= post.category.name %></span></h4>
            </div><!-- END .overlay -->
      
	<% end %>
    </li><!-- END .isotope-item -->
<% end %>
<!-- fim do render de cada post --> 

    
    
        </div><!-- END #isotope-container -->
                
    </div><!-- END #primary-container --> 	
    </div><!-- END #theme-wrapper -->


<div class="hidden-sidebar">

	<div class="hidden-sidebar-inner">
		<!--logo-->
        	
        	<%= link_to "Papo do Dia", root_path, :class => "logo" %>
       		<div class="logo-desc">"com a Neuly"</div>
		<!--logo end-->
        
        <!--navigation-->
        <div class="widget">
            <div class="heading">Categorias</div>
            <div class="textwidget">
            	<ul class="menu">
		<% @categories.each do |category| %>
		<li> <%= link_to "#{category.name}", category %> </li>

	        <% end %>
                   
                </ul>
              
            </div>
        </div>
        <!--navigation end-->
        
     
        
 
        
  
        
  
        

        
        <!--about-->
        <div class="widget">
            <div class="heading">Sobre</div>
            <div class="textwidget">	
            	 Texto relatando sobre o que o blog falará!
            </div>
        </div>
        <!--about end-->
        
        <!--dribbble-->
        <div class="widget widget_bean_dribbble_widget">
            <div class="heading">Facebook</div>
           
        </div>
        <!--dribbble end-->
        
        <!--subscribe-->
        <div class="widget">
            <div class="heading">Publicidade</div>
 
        </div>
        <!--subscribe end-->
        
        <!--recent post-->
        <div class="widget widget_recent_entries">
        	<div class="heading">Últimas postagens</div>
        	<ul>
	<% @posts.each do |post| %>
	        <li><%= link_to "#{post.title}", post %></li>

	<% end %>
			
			</ul>
        </div>
        <!--recent post end-->
        

               
        <p class="copy">© 2014 Todos os direitos reservados. <a href="http://www.ifollowagencia.com.br">iFollow Agência Digital.</a></p>
		
               
               
		
		
	</div><!-- END .hidden-sidebar-inner -->	

</div><!-- END .hidden-sidebar -->	

    		

	

app/views/home/index.html.erb
		
	<div id="theme-wrapper" >
		
			<header>						
		<div class="branding-wrap text-logo hide-for-small">				
		  <ul id="filter" data-filter="isotope-item">
		       
                        <li><a href="#" data-filter="isotope-item" class="tiptip " title="Todos"></a></li>
			<% @categories.each do |category| %>
			<li><%= link_to "#{category.name}", category, {:'data-filter' => category.name, :'title' => category.name } %></li>
			<% end %>
                      
                    </ul>
				</div><!-- END .branding-wrap.hide-for-small -->
					
				<div id="header-container" class="hide-for-small" >
					<span class="menu-icon"></span>
				</div><!-- END #header-container.hide-for-small -->	
			</header>
				
	
		
<div id="primary-container" class="portfolio-template">

<div id="isotope-container" class="animated BeanFadeIn isotope">

<% @posts.each do |post| %>	


<!-- post a post do blog no bloco -->
<li class="portfolio type-portfolio <%= post.category.name %> isotope-item">	
        <span class="overlay-meta-wrapper hover-on">
        <ul>
            <li class="animated BeanBounceIn"><a href="#" class="tweetlink">Twitter Share</a></li>
            <li class="animated BeanBounceIn"><a href="#" class="facelink">Facebook Share</a></li>
          
        </ul>
        </span><!-- END .overlay-meta-wrapper -->
	<%= link_to(post, :class => 'hover-on') do %>
        
            <div class="hoverdiv-feat hide-for-small">
	           <%= image_tag(post.image_url(:giga)) %>
         		
            </div>
            
            <div class="overlay hover-on">
                <h4><%= post.title %> <span><%= post.category.name %></span></h4>
            </div><!-- END .overlay -->
      
	<% end %>
    </li><!-- END .isotope-item -->
<% end %>
<!-- fim do render de cada post --> 

    
    
        </div><!-- END #isotope-container -->
                
    </div><!-- END #primary-container --> 	
    </div><!-- END #theme-wrapper -->


<div class="hidden-sidebar">

	<div class="hidden-sidebar-inner">
		<!--logo-->
        	
        	<%= link_to "Papo do Dia", root_path, :class => "logo" %>
       		<div class="logo-desc">"com a Neuly"</div>
		<!--logo end-->
        
        <!--navigation-->
        <div class="widget">
            <div class="heading">Categorias</div>
            <div class="textwidget">
            	<ul class="menu">
		<% @categories.each do |category| %>
		<li> <%= link_to "#{category.name}", category %> </li>

	        <% end %>
                   
                </ul>
              
            </div>
        </div>
        <!--navigation end-->
        
     
        
 
        
  
        
  
        

        
        <!--about-->
        <div class="widget">
            <div class="heading">Sobre</div>
            <div class="textwidget">	
            	 Texto relatando sobre o que o blog falará!
            </div>
        </div>
        <!--about end-->
        
        <!--dribbble-->
        <div class="widget widget_bean_dribbble_widget">
            <div class="heading">Facebook</div>
           
        </div>
        <!--dribbble end-->
        
        <!--subscribe-->
        <div class="widget">
            <div class="heading">Publicidade</div>
 
        </div>
        <!--subscribe end-->
        
        <!--recent post-->
        <div class="widget widget_recent_entries">
        	<div class="heading">Últimas postagens</div>
        	<ul>
	<% @posts.each do |post| %>
	        <li><%= link_to "#{post.title}", post %></li>

	<% end %>
			
			</ul>
        </div>
        <!--recent post end-->
        

               
        <p class="copy">© 2014 Todos os direitos reservados. <a href="http://www.ifollowagencia.com.br">iFollow Agência Digital.</a></p>
		
               
               
		
		
	</div><!-- END .hidden-sidebar-inner -->	

</div><!-- END .hidden-sidebar -->	

    		

	

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Papo do dia</title>
	
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!--[if !IE]><!-->
<div class="fit-vids-style" id="fit-vids-style" style="display: none;">

­<style>
.fluid-width-video-wrapper{
width:100%;
position:relative;
padding:0;
}
.fluid-width-video-wrapper iframe,.fluid-width-video-wrapper object,.fluid-width-video-wrapper embed {
position:absolute;
top:0;
left:0;
width:100%;
height:100%;
}
</style>
</div>
<script>
if (/*@cc_on!@*/false) {
 document.documentElement.className+=' lt-ie10'; 
}</script>
<!--<![endif]--> 

    <link rel="stylesheet" id="framework-css" href="/css/framework.css" type="text/css" media="all">
    <link rel="stylesheet" id="main-css" href="/css/style.css" type="text/css" media="all">
    <link rel="stylesheet" id="mobile-css" href="/css/mobile.css" type="text/css" media="all">
    <link rel="stylesheet" href="/css/tipTip.css">
    
    <script type="text/javascript" src="/js/jquery.js"></script>
    <script type="text/javascript" src="/js/jquery-migrate.min.js"></script>



</head>

<body>
	
<%= yield %>
<%= render 'shared/javascripts' %>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/pt_PT/all.js#xfbml=1&appId=742682492433145";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post , :html => {:multipart => true}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
 <div class="field">
    <%= f.label :content2 %><br>
    <%= f.text_area :content2 %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
<div class="field">
    <%= f.label :image2 %><br>
    <%= f.file_field :image2 %>
  </div>
  <div class="field">
    <%= f.label :author_id %><br>
    <%= collection_select(:post, :author_id, Author.all, :id, :name, prompt: 'selecione o Autor') %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
   <%= collection_select(:post, :category_id, Category.all, :id, :name, prompt: 'selecione a Categoria') %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Content</th>
      <th>Date</th>
      <th>Image</th>
      <th>Author</th>
      <th>Category</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= post.content %></td>
        <td><%= post.date %></td>
        <td><%= post.image %></td>
        <td><%= post.author %></td>
        <td><%= post.category %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
	<div id="theme-wrapper">
		
			<header>						
		<div class="branding-wrap text-logo hide-for-small">				
		  <ul id="filter" data-filter="isotope-item">
		       
                        <li><a href="#" data-filter="isotope-item" class="tiptip " title="Todos"></a></li>
			<% @categories.each do |category| %>
			<li><%= link_to "", category, {:'data-filter' => category.name, :'title' => category.name } %></li>
			<% end %>
                      
                    </ul>
				</div><!-- END .branding-wrap.hide-for-small -->
					
				<div id="header-container" class="hide-for-small" >
					<span class="menu-icon"></span>
				</div><!-- END #header-container.hide-for-small -->	
			</header>
				
				
	
		
	<div id="primary-container" class="portfolio-template" >
	
    	<div class="work-post format-image">
        	<div class="preview-img">
		<%= image_tag(@post.image_url(:giga)) %>
            	
                <header class="entry-header">
                    <h2><%= @post.title %></h2>
                <span>Data: <%= @post.created_at.strftime(" %m/%h/%Y ") %> Autor: <%= @post.author.name %></span>
                </header><!-- .entry-header -->
            </div>
            <div class="work-content">
            	<h3 class="heading-work"><%#= @post.title %></h3>
                <p>
                	<%= @post.description %>
                </p>
                <p>
                	<%= @post.content %>
                </p>
                <%= image_tag(@post.image2_url(:giga)) %>
                <h3 class="heading-work"> </h3>
                <p><%= @post.content2 %></p>
            </div>
            <div class="clearfix"></div>
            <div class="fb-comments" data-href="<%= request.original_url %>" data-width="800" data-numposts="20" data-colorscheme="light"></div>
            <div class="tags">
<a href="#" rel="tag"><%= @post.category.name %></a> 
            </div>
            <div class="right-work-info">
            	<span class="post-share">
                	<div class="post-share-links">
                    	<a href="https://twitter.com/intent/tweet?=More%20filters!&amp;tw_p=tweetbutton&amp;url=<%= request.original_url %>&amp;text=titile post" target="_blank" class="share-icon fb">Share Facebook</a>
                        <a href="https://www.facebook.com/sharer/sharer.php?u=<%= request.original_url %>" target="_blank" class="share-icon tw">Share Twitter</a>
                     
                    </div>
                </span>
                <a href="#" class="post-like post-like " title="Gostam desta postagem"><div class="post-like-info">0</div></a>
            </div>
            <div class="clearfix"></div>
            
            
        </div>
        
	            
    </div><!-- END #primary-container --> 	
    </div><!-- END #theme-wrapper -->

<div class="hidden-sidebar">

	<div class="hidden-sidebar-inner">
		<!--logo-->
        	
        	<%= link_to "Papo do Dia", root_path, :class => "logo" %>
       		<div class="logo-desc">"com a Neuly"</div>
		<!--logo end-->
        
        <!--navigation-->
        <div class="widget">
            <div class="heading">Categorias</div>
            <div class="textwidget">
            	<ul class="menu">
		<% @categories.each do |category| %>
		<li> <%= link_to "#{category.name}" %> </li>

	        <% end %>
                   
                </ul>
              
            </div>
        </div>
        <!--navigation end-->
        
     
        
 
        
  
        
  
        

        
        <!--about-->
        <div class="widget">
            <div class="heading">Sobre</div>
            <div class="textwidget">	
            	 Texto relatando sobre o que o blog falará!
            </div>
        </div>
        <!--about end-->
        
        <!--dribbble-->
        <div class="widget widget_bean_dribbble_widget">
            <div class="heading">Facebook</div>
           
        </div>
        <!--dribbble end-->
        
        <!--subscribe-->
        <div class="widget">
            <div class="heading">Publicidade</div>
 
        </div>
        <!--subscribe end-->
        
        <!--recent post-->
        <div class="widget widget_recent_entries">
        	<div class="heading">Últimas postagens</div>
        	<ul>
	<% @posts.each do |post| %>
	        <li><%= link_to "#{post.title}", post %></li>

	<% end %>
			
			</ul>
        </div>
        <!--recent post end-->
        

               
        <p class="copy">© 2014 Todos os direitos reservados. <a href="http://www.ifollowagencia.com.br">iFollow Agência Digital.</a></p>
		
               
               
		
		
	</div><!-- END .hidden-sidebar-inner -->	

</div><!-- END .hidden-sidebar -->	

    		

app/views/shared/_javascripts.html.erb
		    	<script type="text/javascript">
		    	
		    	jQuery(document).ready(function($) {
		    	
		    		//HOVERDIV ONLY NORMAL SCREENS
		    		(function($) {
		    		    var $window = $(window),
		    		        $html = $('body');
		    		    function resize() {
		    		        if ($window.width() > 768) {
		    		            return $html.addClass('hoverdiv-active');
		    		        }
		    		        $html.removeClass('hoverdiv-active');
		    		        $html.addClass('no-hoverdiv-active');
		    		    }
		    		    $window
		    		        .resize(resize)
		    		        .trigger('resize');
		    		})(jQuery);
		    		
		    		//HOVERDIV
		    		$(window).bind("load", function() {
		    		   $(' .hoverdiv-active #isotope-container > li ').each( function() { $(this).hoverdir(); } );
		    		});
		    	}); 
		    	</script>

<link rel="stylesheet" id="open-house-styles-css" href="/css/open-house-style.css" type="text/css" media="all">

<script type="text/javascript" src="/js/jquery.fitvids.js"></script>
<script type="text/javascript" src="/js/modernizr.js"></script>
<script type="text/javascript" src="/js/jquery.bxslider.js"></script>
<script type="text/javascript" src="/js/custom.js"></script>
<script type="text/javascript" src="/js/custom-libraries.js"></script>
<script type="text/javascript" src="/js/isotope.js"></script>
<script type="text/javascript" src="/js/jquery.tipTip.minified.js"></script>
<script type="text/javascript" src="/js/hoverdir.js"></script>